# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/evaluation/A/4/test_data_joint.npy
  label_path: ./data/evaluation/A/4/test_label.pkl
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 4
  num_point: 25
  num_person: 1
  in_channels: 3
  num_gcn_scales: 13
  num_g3d_scales: 6
  graph: graph.body_25.AdjMatrixGraph


# test
phase: test
device: 1
test_batch_size: 16
weights: work_dir/paper/A/4/weights/weights-21-3003.pt

work_dir: ./eval/evaluation/evaluation_joint/
save_score: True