
work_dir: ./work_dir/recognition_multi/B/miso_msg3d_joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/recognition_multi/1/C/train_data_joint.npy
  label_path: ./data/recognition_multi/1/C/train_label.pkl
  debug: False

test_feeder_args:
  data_path: ./data/recognition_multi/1/C/valid_data_joint.npy
  label_path: ./data/recognition_multi/1/C/valid_label.pkl

# model
model: model.msg3d_multi.MultiGCN
model_args:
  num_class: 4
  num_point: 25
  num_person: 1
  in_channels: 3
  num_gcn_scales: 13
  num_g3d_scales: 6
  num_view: 1
  graph: graph.body_25.AdjMatrixGraph
  

# optim
optimizer: SGD
# weight_decay: 0.001
weight_decay: 0.001
base_lr: 0.01
#base_lr: 0.01
step: [25, 45, 65]

# training
num_epoch: 100
# device: [0, 1]
device: [0, 1]
# batch_size: 8
batch_size: 8
# forward_batch_size: 8
forward_batch_size: 8
# test_batch_size: 8
test_batch_size: 8
nesterov: True




