
work_dir: ./work_dir/paper_action/B/msg3d_bone

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/paper_action/B/train_data_bone.npy
  label_path: ./data/paper_action/B/train_label.pkl
  debug: False

test_feeder_args:
  data_path: ./data/paper_action/B/test_data_bone.npy
  label_path: ./data/paper_action/B/test_label.pkl

# model
model: model.msg3d.Model
model_args:
  num_class: 4
  num_point: 25
  num_person: 1
  in_channels: 3
  num_gcn_scales: 13
  num_g3d_scales: 6
  graph: graph.body_25.AdjMatrixGraph
  

# optim
# weight_decay: 0.001
weight_decay: 0.001
base_lr: 0.01
#base_lr: 0.01
step: [10, 20, 30]

# training
num_epoch: 40
# device: [0, 1]
device: [0, 1]
# batch_size: 32
batch_size: 32
# forward_batch_size: 32
forward_batch_size: 32
# test_batch_size: 16
test_batch_size: 16
nesterov: True




