# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/paper_action/B/test_data_bone.npy
  label_path: ./data/paper_action/B/test_label.pkl
  debug: False

# model
model: model.msg3d_multi.Multi_GCN
model_args:
  num_class: 4
  num_point: 25
  num_person: 1
  in_channels: 3
  num_gcn_scales: 13
  num_g3d_scales: 6
  graph: graph.kinetics.AdjMatrixGraph
  


# test
phase: test
device: 0
test_batch_size: 16
weights: ./work_dir/miso/GMS/bone/bone_model.pt

work_dir: ./eval/miso/miso_bone/
save_score: True