
work_dir: ./work_dir/recognition_multi/B/miso_msg3d_joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/recognition_multi/123/A/train_data_joint.npy
  label_path: ./data/recognition_multi/123/A/train_label.pkl
  debug: False

test_feeder_args:
  data_path: ./data/recognition_multi/123/A/valid_data_joint.npy
  label_path: ./data/recognition_multi/123/A/valid_label.pkl

# model
model: model.msg3d_multi.MultiGCN
model_args:
  num_class: 4
  num_point: 25
  num_person: 1
  in_channels: 3
  num_gcn_scales: 13
  num_g3d_scales: 6
  graph: graph.body_25.AdjMatrixGraph
  num_view: 3
  

# optim
optimizer: SGD
# weight_decay: 0.001
weight_decay: 0.004
base_lr: 0.01
#base_lr: 0.01
step: [30, 60]

# training
num_epoch: 100
device: [0, 1]
# device: [1]
# batch_size: 8
batch_size: 32
# forward_batch_size: 8
forward_batch_size: 16
# test_batch_size: 8
test_batch_size: 16
nesterov: True


